// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iapqzwgbaaraiavcwmju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhcHF6d2diYWFyYWlhdmN3bWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzQ4MDIsImV4cCI6MjA2NTUxMDgwMn0.ufQaeyvsHaDkX4mPlSB-QhT4pxg5lK0cDPBy2DT0D4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);